//! Canonical entity model.
//!
//! C++ refs:
//! - `game/Entities/Object/Object.h`
//! - `game/Entities/Object/Object.cpp`
//! - `game/Entities/Object/ObjectGuid.h`

mod creature;
mod game_object;
mod object;
mod object_accessor;
mod player;
mod unit;
mod update_fields;
mod world_object;

pub use creature::{
    CREATURE_REGEN_INTERVAL_MS, Creature, CreatureModelDimensions, DEFAULT_BOUNDARY_CHECK_TIME_MS,
    DEFAULT_CORPSE_DELAY_SECS, DEFAULT_MONSTER_SIGHT_DISTANCE, DEFAULT_RESPAWN_DELAY_SECS,
    LOOT_MODE_DEFAULT, MAX_CREATURE_SPELLS, MovementGeneratorType, ReactState,
};
pub use game_object::{
    DEFAULT_GAMEOBJECT_RESPAWN_DELAY_SECS, GAME_OBJECT_DATA_ART_KIT_BIT,
    GAME_OBJECT_DATA_CUSTOM_PARAM_BIT, GAME_OBJECT_DATA_DISPLAY_ID_BIT,
    GAME_OBJECT_DATA_FACTION_TEMPLATE_BIT, GAME_OBJECT_DATA_FLAGS_BIT, GAME_OBJECT_DATA_LEVEL_BIT,
    GAME_OBJECT_DATA_PARENT_BIT, GAME_OBJECT_DATA_PERCENT_HEALTH_BIT, GAME_OBJECT_DATA_STATE_BIT,
    GAME_OBJECT_DATA_TYPE_ID_BIT, GAMEOBJECT_LOOT_MODE_DEFAULT, GameObject, GameObjectDataUpdate,
    GameObjectDataValues, GameObjectValuesUpdate, GoState, LootState,
};
pub use object::{CreateObjectFlags, EntityObject, EntityObjectState, ObjectChangedFields};
pub use object_accessor::{
    AccessorObjectKind, AccessorPlayer, MapObjectRecord, ObjectAccessor, ObjectAccessorError,
    normalize_player_name,
};
pub use player::{
    ACTIVE_PLAYER_DATA_CHARACTER_POINTS_BIT, ACTIVE_PLAYER_DATA_COINAGE_BIT,
    ACTIVE_PLAYER_DATA_INV_SLOTS_FIRST_BIT, ACTIVE_PLAYER_DATA_INV_SLOTS_PARENT_BIT,
    ACTIVE_PLAYER_DATA_NEXT_LEVEL_XP_BIT, ACTIVE_PLAYER_DATA_NUM_BACKPACK_SLOTS_BIT,
    ACTIVE_PLAYER_DATA_PARENT_BIT, ACTIVE_PLAYER_DATA_XP_BIT, ActivePlayerDataUpdate,
    ActivePlayerDataValues, MAX_MONEY_AMOUNT, PLAYER_DATA_CURRENT_SPEC_ID_BIT,
    PLAYER_DATA_FLAGS_BIT, PLAYER_DATA_FLAGS_EX_BIT, PLAYER_DATA_LOOT_TARGET_GUID_BIT,
    PLAYER_DATA_NATIVE_SEX_BIT, PLAYER_DATA_NUM_BANK_SLOTS_BIT, PLAYER_DATA_PARENT_BIT,
    PLAYER_SLOT_END, Player, PlayerDataUpdate, PlayerDataValues, PlayerValuesUpdate, TEAM_OTHER,
};
pub use unit::{
    BASE_MAXDAMAGE, BASE_MINDAMAGE, BASE_MOVE_SPEED, DEFAULT_PLAYER_DISPLAY_SCALE, MAX_ATTACK,
    MAX_MOVE_TYPE, MAX_POWERS, MAX_POWERS_PER_CLASS, UNIT_DATA_BOUNDING_RADIUS_BIT,
    UNIT_DATA_CLASS_ID_BIT, UNIT_DATA_COMBAT_REACH_BIT, UNIT_DATA_DISPLAY_ID_BIT,
    UNIT_DATA_DISPLAY_POWER_BIT, UNIT_DATA_DISPLAY_SCALE_BIT, UNIT_DATA_FACTION_TEMPLATE_BIT,
    UNIT_DATA_FLAGS_BIT, UNIT_DATA_FLAGS2_BIT, UNIT_DATA_FLAGS3_BIT, UNIT_DATA_HEALTH_BIT,
    UNIT_DATA_LEVEL_BIT, UNIT_DATA_MAX_HEALTH_BIT, UNIT_DATA_MAX_POWER_FIRST_BIT,
    UNIT_DATA_NATIVE_DISPLAY_ID_BIT, UNIT_DATA_NATIVE_DISPLAY_SCALE_BIT, UNIT_DATA_PARENT_BIT,
    UNIT_DATA_PLAYER_CLASS_ID_BIT, UNIT_DATA_POWER_FIRST_BIT, UNIT_DATA_POWER_PARENT_BIT,
    UNIT_DATA_RACE_BIT, UNIT_DATA_SEX_BIT, UNIT_DATA_TARGET_BIT, Unit, UnitDataUpdate,
    UnitDataValues, UnitValuesUpdate,
};
pub use update_fields::{
    ACTIVE_PLAYER_DATA_BITS, GAME_OBJECT_DATA_BITS, NUM_CLIENT_OBJECT_TYPES, OBJECT_DATA_BITS,
    OBJECT_DATA_DYNAMIC_FLAGS_BIT, OBJECT_DATA_ENTRY_ID_BIT, OBJECT_DATA_PARENT_BIT,
    OBJECT_DATA_SCALE_BIT, ObjectDataUpdate, ObjectDataValues, PLAYER_DATA_BITS,
    TYPEID_ACTIVE_PLAYER, TYPEID_GAME_OBJECT, TYPEID_OBJECT, TYPEID_PLAYER, TYPEID_UNIT,
    UNIT_DATA_BITS, UpdateMask, ValuesUpdate,
};
pub use world_object::{MAPID_INVALID, MapBindingError, PhaseShift, WorldLocation, WorldObject};
